### PR TITLE
webD-kviz-app with resolved issues

### PR DESCRIPTION
**Pull request by soumyajindal0707**

### CODE REVIEW

**Comment by soumyajindal0707** [comment]
Hi @Alcyone713. I have attached an about.md file to give details about this pull request. Please do check it out

**Comment by Alcyone713** [comment]
Hey, please add some screenshots of whatever changes you have made.

**Comment by soumyajindal0707** [comment]
Hi @Alcyone713. I have uploaded the Readme file with the demo video. Please check it out

**Comment by soumyajindal0707** [comment]
Hi,

I saw that you have only closed #2 issue ( dark-theme option). I have also
added solutions for the other issues.
Pls consider them also. I've worked very hard on it.

**Pull request merged**
